"""Schemas for DOCX export functionality.

This module defines the request/response models for exporting workflow results
to enterprise-grade, auditable DOCX documents.
"""

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field

from src.schemas.clause_redlines import ClauseRedlinesResponse
from src.schemas.contract_review import ContractReviewResponse
from src.schemas.workflow_status import WorkflowResultStatus


class DocumentMetadata(BaseModel):
    """Metadata about the source document for export."""

    document_id: str = Field(..., description="ID of the source document")
    version_id: str = Field(..., description="ID of the source document version")
    document_title: str = Field(..., description="Title of the document")
    version_number: int = Field(1, description="Version number of the document")
    workspace_name: str = Field(..., description="Name of the workspace")
    tenant_name: str = Field(..., description="Name of the tenant/organization")
    jurisdiction: str = Field(..., description="Jurisdiction (UAE, DIFC, ADGM, KSA)")


class ExportRequest(BaseModel):
    """Base request for exporting workflow results."""

    document_metadata: DocumentMetadata = Field(
        ..., description="Metadata about the source document"
    )


class ContractReviewExportRequest(ExportRequest):
    """Request body for contract review DOCX export."""

    workflow_result: ContractReviewResponse = Field(
        ..., description="The complete contract review workflow result"
    )


class ClauseRedlinesExportRequest(ExportRequest):
    """Request body for clause redlines DOCX export."""

    workflow_result: ClauseRedlinesResponse = Field(
        ..., description="The complete clause redlines workflow result"
    )


class ExportErrorResponse(BaseModel):
    """Error response for export failures."""

    error: str = Field(..., description="Error message")
    error_code: str = Field(..., description="Error code for programmatic handling")
    timestamp: datetime = Field(
        default_factory=datetime.utcnow, description="When the error occurred"
    )


# Export-related constants
CONFIDENTIALITY_NOTICE = """CONFIDENTIAL AND PRIVILEGED

This document contains confidential information prepared by Aiden.ai for internal 
review purposes only. This document does not constitute legal advice. The contents 
of this document should not be shared with third parties without prior authorization.
Any reliance on the information contained herein is at the reader's own risk.
"""

LEGAL_DISCLAIMER = """DISCLAIMER

This document is generated by Aiden.ai, an AI-powered legal research and analysis 
platform. The analysis, findings, and recommendations contained herein are based on 
the document(s) provided and the AI system's interpretation thereof.

This document does NOT constitute legal advice. Users should consult with qualified 
legal counsel before making any legal decisions based on the contents of this document.

The accuracy of this analysis depends on the quality and completeness of the source 
documents provided. Aiden.ai makes no warranties, express or implied, regarding the 
completeness, accuracy, or reliability of the information contained herein.
"""


class WorkflowType(str):
    """Workflow type identifiers for export."""

    CONTRACT_REVIEW = "CONTRACT_REVIEW_V1"
    CLAUSE_REDLINES = "CLAUSE_REDLINES_V1"
