"""Curated KSA demo seed fixtures for presentation environments."""

from __future__ import annotations

from typing import Any


def _doc(
    title: str,
    doc_type: str,
    template: str,
    role: str,
    day_offset: int,
    *,
    context: dict[str, Any] | None = None,
) -> dict[str, Any]:
    return {
        "title": title,
        "doc_type": doc_type,
        "template": template,
        "role": role,
        "day_offset": day_offset,
        "context": context or {},
    }


def _note(content: str, day_offset: int, *, amin: bool = False) -> dict[str, Any]:
    return {
        "content": content,
        "day_offset": day_offset,
        "amin": amin,
    }


def _event(
    event_type: str,
    title: str,
    description: str,
    day_offset: int,
) -> dict[str, Any]:
    return {
        "event_type": event_type,
        "title": title,
        "description": description,
        "day_offset": day_offset,
    }


def _client(
    *,
    display_name: str,
    display_name_ar: str,
    client_type: str,
    city: str,
    email: str,
    phone: str,
    address: str,
    cases: list[dict[str, Any]],
    notes: str | None = None,
    trade_name: str | None = None,
    cr_number: str | None = None,
    vat_number: str | None = None,
    sector: str | None = None,
    incorporation_country: str | None = "Saudi Arabia",
    national_id: str | None = None,
    nationality: str | None = None,
    org_type: str | None = None,
) -> dict[str, Any]:
    return {
        "display_name": display_name,
        "display_name_ar": display_name_ar,
        "client_type": client_type,
        "email": email,
        "phone": phone,
        "address": address,
        "trade_name": trade_name,
        "cr_number": cr_number,
        "vat_number": vat_number,
        "sector": sector,
        "incorporation_country": incorporation_country,
        "national_id": national_id,
        "nationality": nationality,
        "org_type": org_type,
        "notes": notes or f"Presentation-grade demo client anchored in {city}.",
        "cases": cases,
    }


def _case(
    *,
    internal_ref: str,
    case_number: str,
    title: str,
    title_ar: str,
    practice_area: str,
    priority: str,
    status: str,
    description: str,
    amin_briefing: str,
    opened_days_ago: int,
    next_deadline_in_days: int | None = None,
    next_deadline_description: str | None = None,
    court_name: str | None = None,
    court_circuit: str | None = None,
    judge_name: str | None = None,
    opposing_party: str | None = None,
    opposing_counsel: str | None = None,
    closed_days_ago: int | None = None,
    documents: list[dict[str, Any]] | None = None,
    notes: list[dict[str, Any]] | None = None,
    events: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    return {
        "internal_ref": internal_ref,
        "case_number": case_number,
        "title": title,
        "title_ar": title_ar,
        "practice_area": practice_area,
        "jurisdiction": "KSA",
        "priority": priority,
        "status": status,
        "court_name": court_name,
        "court_circuit": court_circuit,
        "judge_name": judge_name,
        "opposing_party": opposing_party,
        "opposing_counsel": opposing_counsel,
        "opened_days_ago": opened_days_ago,
        "next_deadline_in_days": next_deadline_in_days,
        "next_deadline_description": next_deadline_description,
        "closed_days_ago": closed_days_ago,
        "description": description,
        "amin_briefing": amin_briefing,
        "documents": documents or [],
        "notes": notes or [],
        "events": events or [],
    }


def _court_bundle(
    matter: str,
    client_name: str,
    city: str,
    *,
    court_name: str,
    counterparty: str,
) -> list[dict[str, Any]]:
    return [
        _doc(
            f"{matter} - Statement of Claim",
            "docx",
            "court_brief",
            "pleading",
            5,
            context={
                "client_name": client_name,
                "matter": matter,
                "city": city,
                "court_name": court_name,
                "counterparty": counterparty,
                "sections": [
                    "Chronology of the dispute and project milestones.",
                    "Contractual payment entitlement and supporting exhibits.",
                    "Saudi law grounds and procedural requests.",
                ],
            },
        ),
        _doc(
            f"{matter} - Evidence Index",
            "xlsx",
            "evidence_index",
            "evidence",
            7,
            context={
                "headers": ["Exhibit", "Arabic Description", "Owner", "Status", "Notes"],
                "rows": [
                    ["C-01", "العقد الأساسي", "Case Team", "Filed", "Signed bilingual version"],
                    ["C-02", "المراسلات الجوهرية", "Client GC", "Ready", "Chronology aligned"],
                    ["C-03", "شهادات الدفع", "Finance", "Pending", "Final stamp awaited"],
                ],
            },
        ),
        _doc(
            f"{matter} - Filing Receipt",
            "pdf",
            "filing_receipt",
            "court_record",
            8,
            context={
                "client_name": client_name,
                "matter": matter,
                "city": city,
                "counterparty": counterparty,
                "sections": [
                    "Electronic filing confirmation issued for demo purposes only.",
                    "Matter registered with bilingual cover references and exhibit bundle count.",
                ],
            },
        ),
        _doc(
            f"{matter} - Client Strategy Update",
            "pptx",
            "status_update",
            "client_update",
            10,
            context={
                "slides": [
                    ("Executive Summary", [f"{matter} remains active in {city}.", "Primary objective is to narrow issues and protect recovery leverage."]),
                    ("Current Position", ["Witness and document record remains favorable.", f"Counterparty position: {counterparty}."]),
                    ("Next Steps", ["Finalize hearing script and Arabic exhibit order.", "Confirm settlement authority with client leadership."]),
                ],
            },
        ),
    ]


def _corporate_bundle(
    matter: str,
    client_name: str,
    city: str,
    *,
    counterparty: str,
) -> list[dict[str, Any]]:
    return [
        _doc(
            f"{matter} - Principal Terms",
            "docx",
            "contract",
            "draft",
            4,
            context={
                "client_name": client_name,
                "matter": matter,
                "counterparty": counterparty,
                "sections": [
                    "Governance and reserved matters tailored for Saudi sponsors.",
                    "Commercial allocation of risk and indemnity framework.",
                    "Execution steps, conditions precedent, and bilingual signing mechanics.",
                ],
            },
        ),
        _doc(
            f"{matter} - Approvals Tracker",
            "xlsx",
            "tracker",
            "tracker",
            6,
            context={
                "headers": ["Workstream", "Owner", "Status", "Due Date", "Comment"],
                "rows": [
                    ["Board approval", "GC Office", "In Progress", "2026-04-20", "Arabic summary requested"],
                    ["CR and UBO pack", "Corporate Team", "Ready", "2026-04-18", "Awaiting signatures"],
                    ["Counterparty mark-up", "Transactions", "Pending", "2026-04-22", "Liability cap open"],
                ],
            },
        ),
        _doc(
            f"{matter} - Board Pack",
            "pptx",
            "board_pack",
            "board_pack",
            8,
            context={
                "slides": [
                    ("Transaction Snapshot", [matter, f"Counterparty: {counterparty}"]),
                    ("Saudi Structuring Points", ["CR scope, shareholder approvals, and signing authority.", "Board and finance committee sequencing captured."]),
                    ("Decision Request", ["Approve negotiation positions.", "Authorize final execution once conditions are met."]),
                ],
            },
        ),
        _doc(
            f"{matter} - Executive Summary",
            "pdf",
            "client_notice",
            "summary",
            9,
            context={
                "client_name": client_name,
                "matter": matter,
                "city": city,
                "sections": [
                    "Presentation summary of the current transaction posture and open commercial points.",
                    "Prepared in a concise client-facing PDF for senior management circulation.",
                ],
            },
        ),
    ]


def _compliance_bundle(
    matter: str,
    client_name: str,
    city: str,
    *,
    regulator: str,
) -> list[dict[str, Any]]:
    return [
        _doc(
            f"{matter} - Advisory Memo",
            "docx",
            "legal_memo",
            "advice",
            4,
            context={
                "recipient": "General Counsel",
                "client_name": client_name,
                "matter": matter,
                "sections": [
                    f"Regulatory position under {regulator}.",
                    "Immediate remediation steps and evidentiary priorities.",
                    "Board-ready recommendations for the next seven days.",
                ],
            },
        ),
        _doc(
            f"{matter} - Remediation Register",
            "xlsx",
            "tracker",
            "tracker",
            6,
            context={
                "headers": ["Item", "Owner", "Regulator", "Status", "Risk"],
                "rows": [
                    ["Policy refresh", "Compliance", regulator, "In Progress", "Medium"],
                    ["Evidence pack", "Operations", regulator, "Open", "High"],
                    ["Arabic notice draft", "External Counsel", regulator, "Ready", "Medium"],
                ],
            },
        ),
        _doc(
            f"{matter} - Regulator Notice Pack",
            "pdf",
            "client_notice",
            "regulator_pack",
            7,
            context={
                "client_name": client_name,
                "matter": matter,
                "sections": [
                    f"Bilingual notice and supporting summary for {regulator}.",
                    "For demo purposes only; no real filing has been made.",
                ],
            },
        ),
        _doc(
            f"{matter} - Steering Committee Update",
            "pptx",
            "status_update",
            "management_update",
            9,
            context={
                "slides": [
                    ("Issue Map", [matter, f"Primary regulator: {regulator}"]),
                    ("Remediation Status", ["Critical actions assigned across legal, compliance, and operations.", "Client leadership receives bilingual summaries only."]),
                    ("Next 72 Hours", ["Finalize submissions and evidence.", "Confirm spokesperson and privilege protocol."]),
                ],
            },
        ),
    ]


def _employment_bundle(
    matter: str,
    client_name: str,
    city: str,
    *,
    employee_name: str,
) -> list[dict[str, Any]]:
    return [
        _doc(
            f"{matter} - Mediation Brief",
            "docx",
            "court_brief",
            "pleading",
            5,
            context={
                "client_name": client_name,
                "matter": matter,
                "counterparty": employee_name,
                "city": city,
                "sections": [
                    "Employment chronology and compensation record.",
                    "Saudi labour law arguments on notice, bonuses, and EOSB.",
                    "Settlement posture and confidentiality protections.",
                ],
            },
        ),
        _doc(
            f"{matter} - Compensation Model",
            "xlsx",
            "fee_schedule",
            "quantum",
            7,
            context={
                "headers": ["Line Item", "Employee Position", "Client Position", "Delta", "Comment"],
                "rows": [
                    ["Bonus", "SAR 650,000", "SAR 180,000", "SAR 470,000", "Subject to conditions"],
                    ["EOSB", "SAR 220,000", "SAR 205,000", "SAR 15,000", "Service period verified"],
                    ["Unused leave", "SAR 48,000", "SAR 31,000", "SAR 17,000", "Needs HR backup"],
                ],
            },
        ),
        _doc(
            f"{matter} - Without Prejudice Offer",
            "pdf",
            "client_notice",
            "settlement",
            8,
            context={
                "client_name": client_name,
                "matter": matter,
                "sections": [
                    "Confidential settlement proposal for mediation use only.",
                    f"Employee side reference: {employee_name}.",
                ],
            },
        ),
        _doc(
            f"{matter} - Management Update",
            "pptx",
            "status_update",
            "management_update",
            9,
            context={
                "slides": [
                    ("Dispute Snapshot", [matter, f"Employee: {employee_name}"]),
                    ("Exposure", ["Primary risk is variable compensation treatment.", "Reputational handling remains sensitive."]),
                    ("Recommended Line", ["Use bilingual mediation script.", "Keep privilege line tight across HR and legal."]),
                ],
            },
        ),
    ]


def _enforcement_bundle(
    matter: str,
    client_name: str,
    city: str,
    *,
    debtor: str,
) -> list[dict[str, Any]]:
    return [
        _doc(
            f"{matter} - Execution Application",
            "docx",
            "court_brief",
            "pleading",
            4,
            context={
                "client_name": client_name,
                "matter": matter,
                "city": city,
                "counterparty": debtor,
                "sections": [
                    "Instrument details, maturity, and debtor history.",
                    "Execution requests and debtor asset tracing status.",
                    "Hearing note and enforcement sequence.",
                ],
            },
        ),
        _doc(
            f"{matter} - Recovery Tracker",
            "xlsx",
            "chronology",
            "tracker",
            6,
            context={
                "headers": ["Date", "Action", "Owner", "Status", "Recovery Impact"],
                "rows": [
                    ["2026-03-01", "Demand served", "Recovery Team", "Done", "High"],
                    ["2026-03-07", "Execution filing", "Litigation", "Done", "High"],
                    ["2026-03-11", "Debtor objection", "Court Liaison", "Open", "Medium"],
                ],
            },
        ),
        _doc(
            f"{matter} - Demand Letter",
            "pdf",
            "client_notice",
            "demand",
            7,
            context={
                "client_name": client_name,
                "matter": matter,
                "sections": [
                    "Formal recovery demand prepared for pre-hearing circulation.",
                    f"Debtor reference: {debtor}.",
                ],
            },
        ),
        _doc(
            f"{matter} - Collections Update",
            "pptx",
            "status_update",
            "client_update",
            8,
            context={
                "slides": [
                    ("Recovery Position", [matter, f"Debtor: {debtor}"]),
                    ("Enforcement Levers", ["Execution court timetable is favorable.", "Document trail is clean and presentation-ready."]),
                    ("Immediate Next Steps", ["Respond to objection.", "Prepare debtor asset note."]),
                ],
            },
        ),
    ]


KSA_DEMO_CLIENTS: list[dict[str, Any]] = [
    _client(
        display_name="Saudi Horizon Urban Development Company",
        display_name_ar="شركة الأفق السعودي للتطوير العمراني",
        client_type="company",
        city="Riyadh",
        email="legal@saudihorizon-ud.sa",
        phone="+966 11 410 2200",
        address="King Fahd Road, Al Olaya, Riyadh 12212",
        trade_name="Horizon Living",
        cr_number="1010923410",
        vat_number="310184552700003",
        sector="Real Estate Development",
        notes="Flagship developer with active projects in Riyadh and Jeddah.",
        cases=[
            _case(
                internal_ref="MOCK-KSA-001",
                case_number="443251890",
                title="North Riyadh EPC Payment Claim",
                title_ar="مطالبة مستحقات عقد الهندسة والمشتريات والإنشاء",
                practice_area="litigation",
                priority="high",
                status="active",
                court_name="Riyadh Commercial Court",
                court_circuit="Second Circuit",
                judge_name="Hon. Abdulrahman Al-Mutairi",
                opposing_party="Najd Build Contracting Company",
                opposing_counsel="Al Bawardi Legal Consultants",
                opened_days_ago=61,
                next_deadline_in_days=4,
                next_deadline_description="Finalize rebuttal bundle and Arabic exhibit order",
                description="Claim for unpaid construction milestones, variation works, and delay damages tied to a mixed-use tower in north Riyadh.",
                amin_briefing="Use this file to show a mature Saudi commercial dispute with a clean hearing path, structured evidence, and a near-term deadline.",
                documents=_court_bundle(
                    "North Riyadh EPC Payment Claim",
                    "Saudi Horizon Urban Development Company",
                    "Riyadh",
                    court_name="Riyadh Commercial Court",
                    counterparty="Najd Build Contracting Company",
                ),
                notes=[
                    _note("Client approved the updated damages model after reviewing the engineer correspondence schedule.", 10),
                    _note("Amin suggests sharpening the Arabic summary for the court-facing chronology and removing duplicate exhibit captions.", 13, amin=True),
                ],
                events=[
                    _event("filing", "Statement of claim submitted", "Claim package filed with the Riyadh Commercial Court together with the first evidence tranche.", 6),
                    _event("hearing", "Case management hearing completed", "Court directed both parties to narrow issues on variation orders and delay causation.", 18),
                ],
            ),
            _case(
                internal_ref="MOCK-KSA-002",
                case_number="2026-CORP-114",
                title="Jeddah Marina SPV Acquisition",
                title_ar="استحواذ شركة مشروع مرسى جدة",
                practice_area="corporate",
                priority="medium",
                status="active",
                opposing_party="Red Sea Capital Partners",
                opened_days_ago=27,
                next_deadline_in_days=8,
                next_deadline_description="Issue bilingual board approval pack",
                description="Acquisition structuring for a special-purpose vehicle owning waterfront hospitality assets in Jeddah.",
                amin_briefing="This is the transactional counterweight to the litigation file and should feel like live sponsor-side work for a Saudi developer.",
                documents=_corporate_bundle(
                    "Jeddah Marina SPV Acquisition",
                    "Saudi Horizon Urban Development Company",
                    "Jeddah",
                    counterparty="Red Sea Capital Partners",
                ),
                notes=[
                    _note("Finance team requested a short Arabic note on escrow mechanics before board circulation.", 7),
                    _note("Execution copy should isolate Saudi governing law changes from purely commercial drafting points.", 9, amin=True),
                ],
                events=[
                    _event("created", "Deal kick-off completed", "Corporate, finance, and tax teams aligned the sign-off timetable and closing assumptions.", 3),
                    _event("deadline_set", "Board pack deadline confirmed", "Chairman's office asked for a bilingual decision paper before the next investment committee meeting.", 11),
                ],
            ),
        ],
    ),
    _client(
        display_name="Jeddah Pearl Hospitality Group",
        display_name_ar="مجموعة جدة بيرل للضيافة",
        client_type="company",
        city="Jeddah",
        email="gc@jeddahpearl.sa",
        phone="+966 12 612 4401",
        address="Corniche Road, Ash Shati, Jeddah 23511",
        trade_name="Pearl Hospitality",
        cr_number="4030241180",
        vat_number="300441105100003",
        sector="Hospitality",
        cases=[
            _case(
                internal_ref="MOCK-KSA-003",
                case_number="2026-HOSP-031",
                title="Hotel Management Agreement Reset",
                title_ar="إعادة هيكلة اتفاقية إدارة الفندق",
                practice_area="corporate",
                priority="medium",
                status="pending",
                opposing_party="International operator consortium",
                opened_days_ago=19,
                next_deadline_in_days=6,
                next_deadline_description="Send operator liability cap options",
                description="Renegotiation of hotel management terms, owner approvals, and performance testing mechanics for a landmark Jeddah asset.",
                amin_briefing="Showcase sophisticated Saudi hospitality contracting work with bilingual deliverables for ownership and operations teams.",
                documents=_corporate_bundle(
                    "Hotel Management Agreement Reset",
                    "Jeddah Pearl Hospitality Group",
                    "Jeddah",
                    counterparty="International operator consortium",
                ),
                notes=[
                    _note("Owner representative wants performance test examples benchmarked against Red Sea destination assets.", 5),
                ],
                events=[
                    _event("created", "Negotiation workstream opened", "Commercial, brand, and technical annex workstreams were separated for faster review.", 2),
                ],
            ),
            _case(
                internal_ref="MOCK-KSA-004",
                case_number="446118204",
                title="General Manager Bonus and Termination Dispute",
                title_ar="نزاع مكافأة وإنهاء خدمة المدير العام",
                practice_area="employment",
                priority="high",
                status="active",
                court_name="Jeddah Labour Court",
                court_circuit="First Circuit",
                opposing_party="Mr. Tareq Al-Ghamdi",
                opposing_counsel="Faris Employment Advocates",
                opened_days_ago=35,
                next_deadline_in_days=2,
                next_deadline_description="Submit mediation authority note",
                description="Dispute over incentive compensation, notice treatment, and end-of-service entitlements after executive termination.",
                amin_briefing="This matter should read as sensitive, executive-level labour work with clear settlement planning and disciplined communications.",
                documents=_employment_bundle(
                    "General Manager Bonus and Termination Dispute",
                    "Jeddah Pearl Hospitality Group",
                    "Jeddah",
                    employee_name="Mr. Tareq Al-Ghamdi",
                ),
                notes=[
                    _note("HR confirmed the final approved bonus memo and the chairman's reservation comments.", 9),
                    _note("Amin recommends a short mediation script that separates commercial goodwill from legal admissions.", 11, amin=True),
                ],
                events=[
                    _event("hearing", "Mandatory labour mediation listed", "Court referred the matter to mediation with a direction to exchange concise compensation schedules.", 15),
                ],
            ),
        ],
    ),
    _client(
        display_name="Eastern Petro Supply Services Company",
        display_name_ar="شركة الشرقية لخدمات التوريد البترولي",
        client_type="company",
        city="Khobar",
        email="claims@easternpetro.sa",
        phone="+966 13 882 1900",
        address="King Salman Road, Al Khobar 34427",
        trade_name="Eastern Petro",
        cr_number="2050197741",
        vat_number="300893220600003",
        sector="Industrial Supply",
        cases=[
            _case(
                internal_ref="MOCK-KSA-005",
                case_number="445891230",
                title="Promissory Note Recovery Against Equipment Vendor",
                title_ar="استرداد سند لأمر ضد مورّد المعدات",
                practice_area="enforcement",
                priority="high",
                status="active",
                court_name="Dammam Execution Court",
                opposing_party="Atlas Field Equipment Co.",
                opened_days_ago=29,
                next_deadline_in_days=5,
                next_deadline_description="Respond to debtor objection and update recovery note",
                description="Execution proceedings concerning unpaid equipment financing secured by a SAR 8.4M promissory note.",
                amin_briefing="Use this to show a fast-moving Saudi recovery file with clean instruments, an objection, and a strong collections narrative.",
                documents=_enforcement_bundle(
                    "Promissory Note Recovery Against Equipment Vendor",
                    "Eastern Petro Supply Services Company",
                    "Dammam",
                    debtor="Atlas Field Equipment Co.",
                ),
                notes=[
                    _note("Original note and supporting acknowledgment letters were hand-delivered by the client's finance controller.", 6),
                ],
                events=[
                    _event("filing", "Execution application lodged", "Execution court application filed with original instrument references and Arabic debtor summary.", 4),
                ],
            ),
            _case(
                internal_ref="MOCK-KSA-006",
                case_number="2026-DR-018",
                title="Offshore Supply Chain Arbitration Strategy",
                title_ar="استراتيجية تحكيم سلسلة التوريد البحرية",
                practice_area="dispute_resolution",
                priority="medium",
                status="on_hold",
                opposing_party="Gulf Marine Engineering LLC",
                opposing_counsel="Bridge Arbitration Chambers",
                opened_days_ago=43,
                next_deadline_in_days=14,
                next_deadline_description="Await final expert quantum report",
                description="Advisory work on whether to commence arbitration over delayed offshore supply contracts and inspection failures.",
                amin_briefing="The file should feel like a pre-arbitration strategic brief where the team is pausing for expert input before filing.",
                documents=_court_bundle(
                    "Offshore Supply Chain Arbitration Strategy",
                    "Eastern Petro Supply Services Company",
                    "Khobar",
                    court_name="Arbitration Strategy File",
                    counterparty="Gulf Marine Engineering LLC",
                ),
                notes=[
                    _note("Operations insists the technical failure sequence must be simplified for management before any filing recommendation.", 8),
                ],
                events=[
                    _event("status_change", "Matter moved to on_hold", "Client requested that filing advice pause until the marine quantum expert completes the final model.", 12),
                ],
            ),
        ],
    ),
    _client(
        display_name="Madinah Advanced Care Hospital Company",
        display_name_ar="شركة مستشفى المدينة للرعاية المتقدمة",
        client_type="company",
        city="Madinah",
        email="regulatory@madinahcare.sa",
        phone="+966 14 845 2210",
        address="King Abdullah Branch Road, Madinah 42313",
        trade_name="Madinah Care",
        cr_number="4650122014",
        vat_number="301155004200003",
        sector="Healthcare",
        cases=[
            _case(
                internal_ref="MOCK-KSA-007",
                case_number="2026-HC-014",
                title="MOH Branch Licensing Review",
                title_ar="مراجعة تراخيص فروع وزارة الصحة",
                practice_area="compliance",
                priority="medium",
                status="active",
                opened_days_ago=21,
                next_deadline_in_days=7,
                next_deadline_description="Finalize bilingual regulator response pack",
                description="Review of branch licensing, physician roster controls, and inspection remediation items for a planned specialist expansion.",
                amin_briefing="This file gives the demo a strong Saudi regulatory-advisory angle with concrete remediation tasks and Ministry-facing deliverables.",
                documents=_compliance_bundle(
                    "MOH Branch Licensing Review",
                    "Madinah Advanced Care Hospital Company",
                    "Madinah",
                    regulator="Ministry of Health",
                ),
                notes=[
                    _note("Client completed the staffing matrix but still needs Arabic signage evidence for the new branch file.", 6),
                    _note("Amin suggests separating licensing deficiencies from broader operational improvements so the regulator note stays tightly scoped.", 8, amin=True),
                ],
                events=[
                    _event("created", "Regulatory review opened", "Matter launched following a pre-inspection planning session with hospital management and compliance.", 2),
                ],
            ),
            _case(
                internal_ref="MOCK-KSA-008",
                case_number="446009117",
                title="Consultant Physician Disciplinary Response",
                title_ar="الرد على مساءلة استشاري طبي",
                practice_area="employment",
                priority="medium",
                status="pending",
                court_name="Madinah Labour Office",
                opposing_party="Dr. Nasser Al-Harithi",
                opened_days_ago=16,
                next_deadline_in_days=9,
                next_deadline_description="Finalize privileged interview note and response strategy",
                description="Advisory file concerning internal disciplinary findings, patient complaint escalation, and settlement positioning.",
                amin_briefing="This should feel like a delicate internal-response matter where legal is coordinating HR, compliance, and reputational controls.",
                documents=_employment_bundle(
                    "Consultant Physician Disciplinary Response",
                    "Madinah Advanced Care Hospital Company",
                    "Madinah",
                    employee_name="Dr. Nasser Al-Harithi",
                ),
                notes=[
                    _note("Medical director requested a separate annex covering committee composition and privilege handling.", 4),
                ],
                events=[
                    _event("created", "Internal response file opened", "Hospital leadership asked for an integrated HR and legal response protocol before meeting the physician.", 2),
                ],
            ),
        ],
    ),
    _client(
        display_name="Makkah Pilgrim Mobility Company",
        display_name_ar="شركة مكة لحلول تنقّل الحجاج",
        client_type="company",
        city="Makkah",
        email="ops.legal@pilgrimmobility.sa",
        phone="+966 12 550 8808",
        address="Ibrahim Al Khalil Road, Makkah 24231",
        trade_name="Pilgrim Mobility",
        cr_number="4030287743",
        vat_number="301247992300003",
        sector="Mobility and Services",
        cases=[
            _case(
                internal_ref="MOCK-KSA-009",
                case_number="2026-DP-022",
                title="Pilgrim App Data Incident Advisory",
                title_ar="استشارة حادثة بيانات لتطبيق الحجاج",
                practice_area="compliance",
                priority="high",
                status="active",
                opened_days_ago=11,
                next_deadline_in_days=2,
                next_deadline_description="Sign off notification assessment and bilingual holding statement",
                description="Urgent advisory on a suspected personal-data incident affecting customer transport and booking records during a peak travel period.",
                amin_briefing="This is the sharp modern-file in the demo: fast moving, regulator-aware, and board-sensitive with bilingual communications.",
                documents=_compliance_bundle(
                    "Pilgrim App Data Incident Advisory",
                    "Makkah Pilgrim Mobility Company",
                    "Makkah",
                    regulator="Saudi Data and AI Authority",
                ),
                notes=[
                    _note("Forensics vendor confirmed that the exposed dataset was limited to booking metadata pending final validation.", 2),
                    _note("Amin flagged that the customer FAQ must match the Arabic holding statement line by line.", 3, amin=True),
                ],
                events=[
                    _event("amin_action", "Privilege protocol activated", "External counsel instructions issued to ring-fence the incident workstream and preserve privilege where possible.", 1),
                ],
            ),
            _case(
                internal_ref="MOCK-KSA-010",
                case_number="445774219",
                title="Hajj Operations Vendor Settlement Dispute",
                title_ar="نزاع تسوية مع مورّد تشغيل موسم الحج",
                practice_area="litigation",
                priority="high",
                status="active",
                court_name="Makkah Commercial Court",
                court_circuit="Commercial Disputes Circuit",
                opposing_party="Safa Fleet Services",
                opposing_counsel="Al Jisr Law Office",
                opened_days_ago=32,
                next_deadline_in_days=6,
                next_deadline_description="Submit translated settlement chronology",
                description="Commercial dispute over transport-service defaults, emergency vehicle substitutions, and withheld vendor payments after the Hajj season.",
                amin_briefing="The case makes the system feel rooted in Saudi operational reality and gives the presenter a vivid but fully fictional Makkah narrative.",
                documents=_court_bundle(
                    "Hajj Operations Vendor Settlement Dispute",
                    "Makkah Pilgrim Mobility Company",
                    "Makkah",
                    court_name="Makkah Commercial Court",
                    counterparty="Safa Fleet Services",
                ),
                notes=[
                    _note("Client wants the settlement chronology simplified for non-legal executives before the next steering call.", 7),
                ],
                events=[
                    _event("hearing", "Procedural hearing listed", "Court directed the parties to focus the next submission on service-level breaches and payment set-off.", 14),
                ],
            ),
        ],
    ),
    _client(
        display_name="Qassim Agriventures LLC",
        display_name_ar="شركة القصيم للمشاريع الزراعية",
        client_type="company",
        city="Buraydah",
        email="legal@qassimagri.sa",
        phone="+966 16 324 7100",
        address="King Abdulaziz Road, Buraydah 52366",
        trade_name="Qassim Agri",
        cr_number="1130088211",
        vat_number="301755220100003",
        sector="Agribusiness",
        cases=[
            _case(
                internal_ref="MOCK-KSA-011",
                case_number="2026-AGR-009",
                title="National Distribution Agreement Renewal",
                title_ar="تجديد اتفاقية التوزيع الوطنية",
                practice_area="corporate",
                priority="medium",
                status="active",
                opposing_party="Gulf Retail Food Company",
                opened_days_ago=24,
                next_deadline_in_days=10,
                next_deadline_description="Finalize rebate and exclusivity options",
                description="Commercial contract refresh covering territorial exclusivity, private-label obligations, and rebate true-up provisions.",
                amin_briefing="This gives the demo a strong mid-market Saudi contracting file that feels routine, commercial, and genuinely used.",
                documents=_corporate_bundle(
                    "National Distribution Agreement Renewal",
                    "Qassim Agriventures LLC",
                    "Buraydah",
                    counterparty="Gulf Retail Food Company",
                ),
                notes=[
                    _note("Sales lead asked for an annex comparing old and proposed exclusivity language in plain Arabic.", 6),
                ],
                events=[
                    _event("created", "Renewal mandate opened", "Commercial and legal teams agreed the first mark-up principles and approval path.", 3),
                ],
            ),
            _case(
                internal_ref="MOCK-KSA-012",
                case_number="2025-REC-219",
                title="Trade Debt Recovery Settlement",
                title_ar="تسوية استرداد دين تجاري",
                practice_area="enforcement",
                priority="low",
                status="closed",
                opposing_party="Al Rawi Cold Chain Services",
                opened_days_ago=67,
                closed_days_ago=5,
                description="Recovery mandate that concluded with structured repayment and a signed release after pre-execution pressure.",
                amin_briefing="A recently closed recovery matter helps the lists feel credible and gives the presenter a clean success story.",
                documents=_enforcement_bundle(
                    "Trade Debt Recovery Settlement",
                    "Qassim Agriventures LLC",
                    "Buraydah",
                    debtor="Al Rawi Cold Chain Services",
                ),
                notes=[
                    _note("Settlement funds cleared and release pages were countersigned by both finance teams.", 11),
                ],
                events=[
                    _event("status_change", "Matter closed", "Final settlement payment received and closure note issued to the client CFO.", 58),
                ],
            ),
        ],
    ),
    _client(
        display_name="Tabuk Frontier Renewable Energy Company",
        display_name_ar="شركة تبوك فرونتير للطاقة المتجددة",
        client_type="company",
        city="Tabuk",
        email="projects@frontierrenewable.sa",
        phone="+966 14 420 9002",
        address="Prince Sultan Road, Tabuk 47312",
        trade_name="Frontier Renewable",
        cr_number="3550174421",
        vat_number="302194880500003",
        sector="Energy and Infrastructure",
        cases=[
            _case(
                internal_ref="MOCK-KSA-013",
                case_number="444781550",
                title="Grid Access Corridor Land Dispute",
                title_ar="نزاع ممرات الوصول لمشروع الربط الكهربائي",
                practice_area="litigation",
                priority="medium",
                status="on_hold",
                court_name="Tabuk General Court",
                opposing_party="Adjacent landowner consortium",
                opened_days_ago=45,
                next_deadline_in_days=17,
                next_deadline_description="Await municipal and surveyor technical report",
                description="Property access and easement dispute affecting a proposed renewable-energy interconnection corridor near Tabuk.",
                amin_briefing="This should feel like a practical land-access file where the team is waiting on technical evidence rather than going silent.",
                documents=_court_bundle(
                    "Grid Access Corridor Land Dispute",
                    "Tabuk Frontier Renewable Energy Company",
                    "Tabuk",
                    court_name="Tabuk General Court",
                    counterparty="Adjacent landowner consortium",
                ),
                notes=[
                    _note("Client asked for status updates only when the municipality survey office moves the technical report.", 10),
                ],
                events=[
                    _event("status_change", "Matter moved to on_hold", "Court activity paused pending the surveyor's technical mapping and municipal access file.", 14),
                ],
            ),
            _case(
                internal_ref="MOCK-KSA-014",
                case_number="2026-ENE-007",
                title="Solar EPC Consortium Governance Pack",
                title_ar="حزمة حوكمة ائتلاف عقد EPC للطاقة الشمسية",
                practice_area="corporate",
                priority="medium",
                status="active",
                opposing_party="International EPC consortium",
                opened_days_ago=22,
                next_deadline_in_days=9,
                next_deadline_description="Deliver sponsor board pack and reserved-matters grid",
                description="Governance and execution package for a Saudi-led consortium bidding on a large solar EPC package in the northwest.",
                amin_briefing="This file demonstrates sponsor-side project governance work tied to Saudi infrastructure growth and cross-border counterparties.",
                documents=_corporate_bundle(
                    "Solar EPC Consortium Governance Pack",
                    "Tabuk Frontier Renewable Energy Company",
                    "Tabuk",
                    counterparty="International EPC consortium",
                ),
                notes=[
                    _note("Client wants the reserved-matters grid translated into an executive Arabic summary for state-linked shareholders.", 6),
                ],
                events=[
                    _event("created", "Governance stream opened", "Bidding and legal teams aligned signing authorities, conflict rules, and escalation thresholds.", 3),
                ],
            ),
        ],
    ),
    _client(
        display_name="Asir Peaks Hospitality Family Office",
        display_name_ar="مكتب عسير بيكس العائلي للضيافة",
        client_type="company",
        city="Abha",
        email="familyoffice@asirpeaks.sa",
        phone="+966 17 227 8800",
        address="King Faisal Road, Abha 62521",
        trade_name="Asir Peaks FO",
        cr_number="5850141107",
        vat_number="302552114200003",
        sector="Family Office",
        cases=[
            _case(
                internal_ref="MOCK-KSA-015",
                case_number="2026-FO-077",
                title="Family Charter and Succession Reset",
                title_ar="إعادة ضبط ميثاق العائلة وخطة الخلافة",
                practice_area="compliance",
                priority="medium",
                status="active",
                opened_days_ago=23,
                next_deadline_in_days=8,
                next_deadline_description="Circulate charter redline and governance matrix",
                description="Governance review for a family office with hospitality and tourism assets, covering committees, delegation, and succession mechanics.",
                amin_briefing="This file broadens the dataset beyond pure corporate clients while still feeling distinctly Saudi and high-value.",
                documents=_compliance_bundle(
                    "Family Charter and Succession Reset",
                    "Asir Peaks Hospitality Family Office",
                    "Abha",
                    regulator="Internal Governance Committee",
                ),
                notes=[
                    _note("Family principal asked for a discreet version of the action register with no names on the cover page.", 5),
                    _note("Amin recommends separating immediate succession actions from long-term governance reforms so the family can approve in stages.", 7, amin=True),
                ],
                events=[
                    _event("created", "Governance review launched", "Scope confirmed with the family office GC and chairman's private office.", 2),
                ],
            ),
            _case(
                internal_ref="MOCK-KSA-016",
                case_number="2026-MA-024",
                title="Boutique Hotel Acquisition Due Diligence",
                title_ar="العناية الواجبة لاستحواذ فندق بوتيك",
                practice_area="corporate",
                priority="medium",
                status="pending",
                opposing_party="Founding shareholders of mountain resort SPV",
                opened_days_ago=18,
                next_deadline_in_days=11,
                next_deadline_description="Deliver due diligence red-flag summary",
                description="Buy-side due diligence and SPA structuring for a hospitality acquisition in the Asir region.",
                amin_briefing="This matter reinforces the family-office narrative with a transaction that feels live, commercial, and region-specific.",
                documents=_corporate_bundle(
                    "Boutique Hotel Acquisition Due Diligence",
                    "Asir Peaks Hospitality Family Office",
                    "Abha",
                    counterparty="Founding shareholders of mountain resort SPV",
                ),
                notes=[
                    _note("Tax and title findings need to be split into separate Arabic and English summaries for the investment committee.", 6),
                ],
                events=[
                    _event("created", "Diligence stream opened", "Vendor room access granted and legal diligence checklists circulated.", 2),
                ],
            ),
        ],
    ),
    _client(
        display_name="Ajyal Community Association",
        display_name_ar="جمعية أجيال المجتمعية",
        client_type="organisation",
        city="Riyadh",
        email="governance@ajyal.org.sa",
        phone="+966 11 480 2007",
        address="Imam Saud Road, Riyadh 12474",
        org_type="non-profit",
        notes="Representative nonprofit client for donor and governance work.",
        cases=[
            _case(
                internal_ref="MOCK-KSA-017",
                case_number="2026-NPO-008",
                title="Donor Governance and Grant Conditions Review",
                title_ar="مراجعة حوكمة المانحين وشروط المنح",
                practice_area="compliance",
                priority="low",
                status="active",
                opened_days_ago=26,
                next_deadline_in_days=12,
                next_deadline_description="Issue comments on donor reporting schedule",
                description="Governance review of grant conditions, delegated signing thresholds, and donor-facing reporting commitments.",
                amin_briefing="This broadens the client mix and gives the presenter a clean governance file with public-interest flavor.",
                documents=_compliance_bundle(
                    "Donor Governance and Grant Conditions Review",
                    "Ajyal Community Association",
                    "Riyadh",
                    regulator="National Center for Non-Profit Sector",
                ),
                notes=[
                    _note("Association leadership asked for a one-page Arabic summary showing who can sign grant amendments.", 8),
                ],
                events=[
                    _event("created", "Governance review initiated", "Scope approved by the association chair and donor relations lead.", 3),
                ],
            ),
            _case(
                internal_ref="MOCK-KSA-018",
                case_number="445340002",
                title="Programme Director Separation Settlement",
                title_ar="تسوية إنهاء علاقة مدير البرامج",
                practice_area="employment",
                priority="low",
                status="closed",
                opposing_party="Former programme director",
                opened_days_ago=48,
                closed_days_ago=9,
                description="Employment separation matter resolved through a confidential settlement and handover protocol.",
                amin_briefing="A closed nonprofit employment file helps the system feel like a real portfolio rather than a demo-only queue of open matters.",
                documents=_employment_bundle(
                    "Programme Director Separation Settlement",
                    "Ajyal Community Association",
                    "Riyadh",
                    employee_name="Former programme director",
                ),
                notes=[
                    _note("Settlement deed signed and handover checklist completed by both sides.", 12),
                ],
                events=[
                    _event("status_change", "Matter closed", "Settlement terms were completed and the association confirmed a clean operational handover.", 39),
                ],
            ),
        ],
    ),
    _client(
        display_name="Faisal Al-Qahtani",
        display_name_ar="فيصل القحطاني",
        client_type="individual",
        city="Riyadh",
        email="faisal.qahtani@email.com",
        phone="+966 55 720 1890",
        address="Al Yasmin District, Riyadh 13326",
        national_id="1098765432",
        nationality="Saudi",
        cases=[
            _case(
                internal_ref="MOCK-KSA-019",
                case_number="445602114",
                title="Executive Employment Bonus Claim",
                title_ar="مطالبة مكافأة تنفيذية",
                practice_area="employment",
                priority="high",
                status="active",
                court_name="Riyadh Labour Court",
                opposing_party="Gulf Manufacturing Holding",
                opposing_counsel="Mubarak & Co.",
                opened_days_ago=34,
                next_deadline_in_days=4,
                next_deadline_description="Submit witness summary before final session",
                description="Private-client labour claim concerning unpaid bonus, restricted stock cash-out, and end-of-service entitlements.",
                amin_briefing="This case adds a relatable senior-executive dispute to the portfolio and gives the dashboard another urgent active matter.",
                documents=_employment_bundle(
                    "Executive Employment Bonus Claim",
                    "Faisal Al-Qahtani",
                    "Riyadh",
                    employee_name="Faisal Al-Qahtani",
                ),
                notes=[
                    _note("Client approved the minimum settlement floor but wants to finish the hearing cycle unless payment terms materially improve.", 9),
                ],
                events=[
                    _event("hearing", "Final labour session listed", "Court directed both parties to exchange concise witness summaries before the next hearing.", 16),
                ],
            ),
            _case(
                internal_ref="MOCK-KSA-020",
                case_number="444991208",
                title="Residential Boundary and Easement Dispute",
                title_ar="نزاع حدود وارتفاق عقاري سكني",
                practice_area="litigation",
                priority="medium",
                status="on_hold",
                court_name="Riyadh General Court",
                opposing_party="Adjacent landowner",
                opened_days_ago=41,
                next_deadline_in_days=18,
                next_deadline_description="Await municipality technical report",
                description="Property dispute concerning access rights, shared boundary lines, and encroachment allegations in a north Riyadh villa district.",
                amin_briefing="This file gives the demo a very human private-client story with a realistic external dependency driving the on-hold status.",
                documents=_court_bundle(
                    "Residential Boundary and Easement Dispute",
                    "Faisal Al-Qahtani",
                    "Riyadh",
                    court_name="Riyadh General Court",
                    counterparty="Adjacent landowner",
                ),
                notes=[
                    _note("Municipality survey request submitted; client asked for weekly status updates only when there is movement.", 10),
                ],
                events=[
                    _event("status_change", "Status changed to on_hold", "Matter paused pending municipality survey output and technical sketches.", 13),
                ],
            ),
        ],
    ),
    _client(
        display_name="Sara Al-Harbi",
        display_name_ar="سارة الحربي",
        client_type="individual",
        city="Jeddah",
        email="s.harbi@email.com",
        phone="+966 50 112 7740",
        address="Al Zahra District, Jeddah 23424",
        national_id="1084456671",
        nationality="Saudi",
        cases=[
            _case(
                internal_ref="MOCK-KSA-021",
                case_number="2026-PC-011",
                title="Inheritance Asset Partition Advisory",
                title_ar="استشارة قسمة أصول التركة",
                practice_area="corporate",
                priority="medium",
                status="active",
                opened_days_ago=28,
                next_deadline_in_days=7,
                next_deadline_description="Share bilingual succession roadmap with family representatives",
                description="Advisory mandate on estate-asset partition, family shareholdings, and board reconstitution after succession.",
                amin_briefing="This is a polished private-client advisory matter that still feels commercial and Saudi-specific, not generic estates work.",
                documents=_corporate_bundle(
                    "Inheritance Asset Partition Advisory",
                    "Sara Al-Harbi",
                    "Jeddah",
                    counterparty="Family representatives and trustee advisors",
                ),
                notes=[
                    _note("Client requested that immediate operational actions be separated from long-term governance recommendations.", 8),
                ],
                events=[
                    _event("created", "Succession workstream opened", "Kick-off completed with family representatives, accountants, and corporate advisers.", 4),
                ],
            ),
            _case(
                internal_ref="MOCK-KSA-022",
                case_number="2024-REC-219",
                title="Private Debt Recovery Settlement",
                title_ar="تسوية استرداد دين خاص",
                practice_area="enforcement",
                priority="low",
                status="closed",
                opposing_party="Former business associate",
                opened_days_ago=69,
                closed_days_ago=6,
                description="Private recovery mandate resolved through a negotiated payment plan, guarantee release, and final settlement memorandum.",
                amin_briefing="A recently closed private-client file makes the system feel used and gives the presenter another success outcome to reference.",
                documents=_enforcement_bundle(
                    "Private Debt Recovery Settlement",
                    "Sara Al-Harbi",
                    "Jeddah",
                    debtor="Former business associate",
                ),
                notes=[
                    _note("Settlement funds received in full and release pages countersigned by both parties.", 11),
                ],
                events=[
                    _event("status_change", "Matter closed", "Payment received in full and settlement release issued to the client.", 58),
                ],
            ),
        ],
    ),
]
